name: pipeline
on:
  push:

jobs:
  check-ui:
    name: Check ui on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['10']
        os: [ubuntu-latest, windows-latest]
    defaults:
      run:
        working-directory: organizer-ui
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install packages
        run: npm install
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
  check-api:
    name: Check api on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['10']
        os: [ubuntu-latest, windows-latest]
    defaults:
      run:
        working-directory: organizer-api
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install packages
        run: npm install
      - name: Test
        run: npm run test
